### ISSUE TITLE
Server: use rust refresh command

### ISSUE THREAD

**Issue by nygrenh** [rage/tmc-server#7]
* Runs in background-daemon
* Saves progress to a database table
* Progress indication in the UI with a progress bar and the current phase

```
create_table "course_refreshes"
  t.datetime "created_at"
  t.datetime "updated_at"
  t.integer "course_template_id", null: false
  t.integer "status", null: false, default: 0 # (enum: [:not_started, :in_progress, :complete , :crashed] https://api.rubyonrails.org/v5.2.4.4/classes/ActiveRecord/Enum.html)
  t.integer "creator_id", null: false

create_table "course_refresh_phase_timings" # From tmc-langs-rust coming in as phases complete. Will be used to calculate the length of the progress bar.
  t.integer "course_refresh_id", null: false
  t.string "phase_name:, null: false
  t.integer: "time_ms", null: false
```

**Comment by sebazai** [comment]
`{
    "output-kind":"output-data",
    "status":"finished",
    "message":"refreshed course test-python-ohpe",
    "result":"executed-command",
    "percent-done":1.0,
    "data":
    {
        "new-cache-path":"/path/to_file",
        "course-options" : any 
        "exercises": [
            {
                name: "osa03-24_monta",
                checksum: "taman-tehtavan-checksum",
                points: [ 
                    {
                        "name": "3-24.ekapiste",
                        "requires_review": true
                    }, 
                    {
                        "name": "3-24.tokapiste",
                        "requires_review": false
                    }
                ]
                metadata: "????",
            }
        ]
    }
}`

When data in this format from tmc-lang-rust, nuke all useless code from course_refresher and do all exercise updates in one for loop and small amount of database queries.

- [x] Rework UI accordingly
- [x] Fix specs

**Comment by sebazai** [comment]
TMC-langs data rework started. Rethink Refresh on server.

Possible idea:
1. [x] Course refresh initialized by teacher/admin/someone with access
2. [x] Generate DB instance (CourseRefresh), status: not_started
3. [x] Refresh course page for user with notice: eg. Refresh initialized. Progress reported below, Please wait... 
4. [x] BG: ActionCable report that refresh started -> Disable Refresh button  for all teacher users
3. [x] BG: Background daemon starts course-refresh command
4. [x] BG: Rust magic in background while reporting progress with ActionCable to all teacher users. (Save phases to CourseRefreshPhaseTimings)
5. [x] BG: When Rust done, update server database accordingly or report error and rollback.
6. [x] BG: Generate a (error) report to user to database (CourseRefreshReport)
7. [x] BG: ActionCable send request to refresh site with parameter of CourseRefresh instance ID
8. [x] Refresh page with the report for all users that received the websocket data

Problems to think about are:
- ~~How to implement state that refresh is in progress if someone lands at the page, so that refresh is disabled and he gets live reports of the progress once websocket has connected~~
- Could step 3 be done without refresh, so socket doesn't loose connection?

**Comment by sebazai** [comment]
More to-do:
https://github.com/testmycode/tmc-server/pull/514
